///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddUser recording.
    /// </summary>
    [TestModule("7052a869-7527-47b2-bc06-7defc21e11f9", ModuleType.Recording, 1)]
    public partial class AddUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDemoAppRepository repository.
        /// </summary>
        public static RxDemoAppRepository repo = RxDemoAppRepository.Instance;

        static AddUser instance = new AddUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddUser()
        {
            FirstName = "Jason";
            LastName = "Yamada";
            Age = "30";
            Department = "Office";
            Gender = "Male";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddUser Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("32756adc-177e-45b9-b4f1-d8815e2d8e84")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("40468558-78f1-483f-b9bd-b060ef980561")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        string _Age;

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("b39a4b0f-453e-4ba0-8295-e00ae59458aa")]
        public string Age
        {
            get { return _Age; }
            set { _Age = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("0cb199d1-4d26-4669-8ef6-258287dc35fc")]
        public string Department
        {
            get { return repo.Department; }
            set { repo.Department = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("71a16ccd-41c1-4abf-b83c-a9640ff08650")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$FirstName' on item 'RxMainFrame.RxTabStandard.FirstName'.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.FirstName.Element.SetAttributeValue("Text", FirstName);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$LastName' on item 'RxMainFrame.RxTabStandard.LastName'.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.LastName.Element.SetAttributeValue("Text", LastName);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RxMainFrame.RxTabStandard.Open'.", repo.RxMainFrame.RxTabStandard.OpenInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.Open.Press();
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.Department'.", repo.List1000.DepartmentInfo, new RecordItemIndex(3));
            repo.List1000.Department.Select();
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.TestDatabase'.", repo.RxMainFrame.TestDatabaseInfo, new RecordItemIndex(4));
            repo.RxMainFrame.TestDatabase.Select();
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Age' on item 'RxMainFrame.RxTabStandard.Age'.", repo.RxMainFrame.RxTabStandard.AgeInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Age.Element.SetAttributeValue("Text", Age);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.RxTabStandard.Gender'.", repo.RxMainFrame.RxTabStandard.GenderInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabStandard.Gender.Select();
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RxMainFrame.RxTabStandard.BtnAddPerson'.", repo.RxMainFrame.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.BtnAddPerson.Press();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
