///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemoAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2487c37c-b1d4-44b6-9ade-c473d35fe1c6")]
    public partial class RxDemoAppRepository : RepoGenBaseFolder
    {
        static RxDemoAppRepository instance = new RxDemoAppRepository();
        RxDemoAppRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        RxDemoAppRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemoAppRepository element repository.
        /// </summary>
        [RepositoryFolder("2487c37c-b1d4-44b6-9ade-c473d35fe1c6")]
        public static RxDemoAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemoAppRepository() 
            : base("RxDemoAppRepository", "/", null, 0, false, "2487c37c-b1d4-44b6-9ade-c473d35fe1c6", ".\\RepositoryImages\\RxDemoAppRepository2487c37c.rximgres")
        {
            _rxmainframe = new RxDemoAppRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new RxDemoAppRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _Department = "Office";

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("e454d04c-02ba-4c3e-ae2e-c3bb6129b48e")]
        public string Department
        {
            get { return _Department; }
            set { _Department = value; }
        }

        string _Gender = "Male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("1e6a1620-13b2-4c68-b5cd-d1887115e867")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2487c37c-b1d4-44b6-9ade-c473d35fe1c6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("47ea9809-95e4-49b7-8a84-7b286e60ec05")]
        public virtual RxDemoAppRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("b7aecb2b-772a-4015-8396-aa43f7bd689f")]
        public virtual RxDemoAppRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemoAppRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("47ea9809-95e4-49b7-8a84-7b286e60ec05")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDemoAppRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _testdatabaseInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "47ea9809-95e4-49b7-8a84-7b286e60ec05", "")
            {
                _rxtabstandard = new RxDemoAppRepositoryFolders.RxTabStandardFolder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "154413b4-9f4f-400a-9310-d9e9f9456625");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("47ea9809-95e4-49b7-8a84-7b286e60ec05")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("47ea9809-95e4-49b7-8a84-7b286e60ec05")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("154413b4-9f4f-400a-9310-d9e9f9456625")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("154413b4-9f4f-400a-9310-d9e9f9456625")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("998ebcf1-8e87-4698-9e62-3722bb37b4fd")]
            public virtual RxDemoAppRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("998ebcf1-8e87-4698-9e62-3722bb37b4fd")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _jasonyamadamale30officeInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "998ebcf1-8e87-4698-9e62-3722bb37b4fd", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "9972df42-4916-4302-88ef-1c65e670e548");
                _genderInfo = new RepoItemInfo(this, "Gender", "?/?/radiobutton[@controltext=$Gender]", "", 30000, null, "c46d8aa0-6e19-4935-8b60-6dc564c65b2e");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "415ec819-b109-481e-87cf-08272645cf84");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "a2604c9f-ce14-4cc5-9bd4-e0de173b9da6");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "5268613a-4835-4c6e-83e7-7b95234b35a1");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", "", 30000, null, "97274145-d792-4de1-8f17-ed411d87d07e");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", "", 30000, null, "1cc05cbf-378e-4deb-a2ed-66f55724d06b");
                _jasonyamadamale30officeInfo = new RepoItemInfo(this, "JasonYamadaMale30Office", "list[@controlname='lstPersonList']/?/?/listitem[1]", "", 30000, null, "4403e57c-b3a6-472d-84c9-8c00cebe4bd7");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "8f6eea2e-c7a2-4fa4-b00f-6a2a66a85ccc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("998ebcf1-8e87-4698-9e62-3722bb37b4fd")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("998ebcf1-8e87-4698-9e62-3722bb37b4fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("9972df42-4916-4302-88ef-1c65e670e548")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("9972df42-4916-4302-88ef-1c65e670e548")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("c46d8aa0-6e19-4935-8b60-6dc564c65b2e")]
            public virtual Ranorex.RadioButton Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("c46d8aa0-6e19-4935-8b60-6dc564c65b2e")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("415ec819-b109-481e-87cf-08272645cf84")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("415ec819-b109-481e-87cf-08272645cf84")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("a2604c9f-ce14-4cc5-9bd4-e0de173b9da6")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("a2604c9f-ce14-4cc5-9bd4-e0de173b9da6")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("5268613a-4835-4c6e-83e7-7b95234b35a1")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("5268613a-4835-4c6e-83e7-7b95234b35a1")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("97274145-d792-4de1-8f17-ed411d87d07e")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("97274145-d792-4de1-8f17-ed411d87d07e")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("1cc05cbf-378e-4deb-a2ed-66f55724d06b")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("1cc05cbf-378e-4deb-a2ed-66f55724d06b")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The JasonYamadaMale30Office item.
            /// </summary>
            [RepositoryItem("4403e57c-b3a6-472d-84c9-8c00cebe4bd7")]
            public virtual Ranorex.ListItem JasonYamadaMale30Office
            {
                get
                {
                    return _jasonyamadamale30officeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The JasonYamadaMale30Office item info.
            /// </summary>
            [RepositoryItemInfo("4403e57c-b3a6-472d-84c9-8c00cebe4bd7")]
            public virtual RepoItemInfo JasonYamadaMale30OfficeInfo
            {
                get
                {
                    return _jasonyamadamale30officeInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("8f6eea2e-c7a2-4fa4-b00f-6a2a66a85ccc")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("8f6eea2e-c7a2-4fa4-b00f-6a2a66a85ccc")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("b7aecb2b-772a-4015-8396-aa43f7bd689f")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departmentInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "b7aecb2b-772a-4015-8396-aa43f7bd689f", "")
            {
                _departmentInfo = new RepoItemInfo(this, "Department", "listitem[@text=$Department]", "", 30000, null, "ed7edacc-0b34-44a6-9bab-3a5ea556b1e6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7aecb2b-772a-4015-8396-aa43f7bd689f")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7aecb2b-772a-4015-8396-aa43f7bd689f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Department item.
            /// </summary>
            [RepositoryItem("ed7edacc-0b34-44a6-9bab-3a5ea556b1e6")]
            public virtual Ranorex.ListItem Department
            {
                get
                {
                    return _departmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Department item info.
            /// </summary>
            [RepositoryItemInfo("ed7edacc-0b34-44a6-9bab-3a5ea556b1e6")]
            public virtual RepoItemInfo DepartmentInfo
            {
                get
                {
                    return _departmentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
