///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexWebTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexWebTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6c82bfce-69ec-4fd2-92a3-2b7e1f8983e0")]
    public partial class RanorexWebTestRepository : RepoGenBaseFolder
    {
        static RanorexWebTestRepository instance = new RanorexWebTestRepository();
        RanorexWebTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        RanorexWebTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexWebTestRepository element repository.
        /// </summary>
        [RepositoryFolder("6c82bfce-69ec-4fd2-92a3-2b7e1f8983e0")]
        public static RanorexWebTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexWebTestRepository() 
            : base("RanorexWebTestRepository", "/", null, 0, false, "6c82bfce-69ec-4fd2-92a3-2b7e1f8983e0", ".\\RepositoryImages\\RanorexWebTestRepository6c82bfce.rximgres")
        {
            _applicationundertest = new RanorexWebTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _ranorexvipdatabasetestwebapplicatio = new RanorexWebTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6c82bfce-69ec-4fd2-92a3-2b7e1f8983e0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ba550f2b-5c46-4598-b6eb-8cc4615a81bc")]
        public virtual RanorexWebTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("850aea46-ed68-412c-a545-8f6e2832cfff")]
        public virtual RanorexWebTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexWebTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ba550f2b-5c46-4598-b6eb-8cc4615a81bc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "ba550f2b-5c46-4598-b6eb-8cc4615a81bc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba550f2b-5c46-4598-b6eb-8cc4615a81bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba550f2b-5c46-4598-b6eb-8cc4615a81bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("850aea46-ed68-412c-a545-8f6e2832cfff")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/form[@title>'Ranorex VIP Database Test']", parentFolder, 30000, null, true, "850aea46-ed68-412c-a545-8f6e2832cfff", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Ranorex VIP Database Test']/container/container[2]/container[1]", "", 30000, null, "47b181a0-56a9-40f2-8754-d5b1804b77ca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("850aea46-ed68-412c-a545-8f6e2832cfff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("850aea46-ed68-412c-a545-8f6e2832cfff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("47b181a0-56a9-40f2-8754-d5b1804b77ca")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("47b181a0-56a9-40f2-8754-d5b1804b77ca")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
